#  Pod manifest (chapter 5)
apiVersion: v1
kind: Pod

metadata:
  name: kuard
  labels:
    app: kuard-app
    environment: localdev
    author: ashraf-minhaj
  annotations:
    kuard-icon: "http://someicon.com/someicon"

spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuard
      # checks for application liveness
      # this is container specific
      # 200 => status < 400. Another is readyness
      livenessProbe: 
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 10
        failureThreshold: 3
      readinessProbe:          # is the application ready? not readyness, it's i.
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      # requests - minimum, limit - max
      # resources can be allocated to the container
      # it's per container, not per pod
      resources:
        requests:
          cpu: "500m"       # half CPU
          memory: "128Mi"   # 128MegaByte
        limits:
          cpu: "1000m"
          memory: "256Mi"
      # volumes:
      #   - name: "kuard-data"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP